-- Inputs used by symptom_based_vitamin_deficiency_dataset_final.csv.
-- The target label is generated by the model and is never entered by the nurse.
ALTER TABLE student_health_inputs
  ADD COLUMN living_environment varchar(10) DEFAULT NULL,
  ADD COLUMN skin_condition varchar(30) DEFAULT NULL,
  ADD COLUMN has_dry_eyes varchar(10) DEFAULT NULL,
  ADD COLUMN has_shortness_of_breath varchar(10) DEFAULT NULL,
  ADD COLUMN has_fast_heart_rate varchar(10) DEFAULT NULL,
  ADD COLUMN has_brittle_nails varchar(10) DEFAULT NULL,
  ADD COLUMN has_weight_loss varchar(10) DEFAULT NULL,
  ADD COLUMN has_reduced_wound_healing varchar(10) DEFAULT NULL;
